assemble:
# nasm -f bin hello.asm -o hello
# @chmod +x hello

# nasm -f elf64 hello2.asm -o hello2.o
# ld hello2.o -o hello2

	nasm -f bin hello2.asm

# gcc -O3 exec.c -o exec
# gcc -c -O3 exec.c

clean:
	rm -Rf *~ hello hello2 exec *.o
